# Generated by Django 3.1.1 on 2020-11-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsInformation',
            fields=[
                ('DIid', models.AutoField(primary_key=True, serialize=False)),
                ('DIrow', models.CharField(max_length=100000)),
            ],
        ),
    ]
